---
name: CodeOwners

on:
  push:
    branches:
      - master
      - main
    paths:
      - CODEOWNERS
      - .github/CODEOWNERS
  pull_request:
    branches:
      - master
      - main
    paths:
      - CODEOWNERS
      - .github/CODEOWNERS
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  validate:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Validate CODEOWNERS
    uses: HariSekhon/GitHub-Actions/.github/workflows/codeowners.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
