---
name: ShellCheck

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.sh'
      - .github/workflows/shellcheck.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.sh'
      - .github/workflows/shellcheck.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  shellcheck:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: ShellCheck
    uses: HariSekhon/GitHub-Actions/.github/workflows/shellcheck.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
