---
name: tfsec

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:
  #schedule:
  #  - cron: '30 0 * * 1'

jobs:
  tfsec:
    name: tfsec
    uses: ta543/GitHub-Actions/.github/workflows/tfsec.yaml@master
    permissions:
      actions: read
      contents: read
      security-events: write
