---
name: Trivy

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  actions: read
  contents: read
  security-events: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  trivy:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Trivy
    uses: HariSekhon/GitHub-Actions/.github/workflows/trivy.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
