---
name: XML

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.xml'
      - .github/workflows/xml.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.xml'
      - .github/workflows/xml.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  check_xml:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Check XML
    uses: HariSekhon/GitHub-Actions/.github/workflows/xml.yaml@master
