---
name: YAML

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - .github/workflows/yaml.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.yml'
      - '**/*.yaml'
      - .github/workflows/yaml.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  check_yaml:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Check YAML
    uses: HariSekhon/GitHub-Actions/.github/workflows/yaml.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
