---
compact: true
directory:
  - .
download-external-modules: true  # without this gets lots of annoying warning lines such as '2022-02-22 16:14:40,180 [MainThread  ] [WARNI]  Failed to download module x/y/z:n.n.n'
framework:
  - all
output: cli
quiet: true
repo-id: HariSekhon/Terraform  # what to report to Bridgecrew Cloud - without this gets annoying duplicate repos such as 'harisekhon_cli_repo/<myrepo>'
soft-fail: true
# https://www.checkov.io/5.Policy%20Index/all.html
skip-check:
  # Ensure at least two approving reviews for PRs
  - CKV_GIT_5
  # Ensure all commits GPG signed
  - CKV_GIT_6
